build: fix errors when linking plugins against procps-ng newlib
Build the link errors:

    /usr/bin/ld: ../lib/libutils.a(vminfo_procps.o): in function `proc_vmem_new':
    vminfo_procps.c:(.text+0x2b): undefined reference to `procps_vmstat_new'
    /usr/bin/ld: ../lib/libutils.a(vminfo_procps.o): in function `proc_vmem_unref':
    vminfo_procps.c:(.text+0x70): undefined reference to `procps_vmstat_unref'
    /usr/bin/ld: ../lib/libutils.a(vminfo_procps.o): in function `proc_vmem_get_pgfault':
    vminfo_procps.c:(.text+0x9b): undefined reference to `procps_vmstat_get'
    /usr/bin/ld: ../lib/libutils.a(vminfo_procps.o): in function `proc_vmem_get_pgfree':
    vminfo_procps.c:(.text+0xce): undefined reference to `procps_vmstat_get'
    /usr/bin/ld: ../lib/libutils.a(vminfo_procps.o): in function `proc_vmem_get_pgmajfault':
    vminfo_procps.c:(.text+0x101): undefined reference to `procps_vmstat_get'
    /usr/bin/ld: ../lib/libutils.a(vminfo_procps.o): in function `proc_vmem_get_pgpgin':
    vminfo_procps.c:(.text+0x134): undefined reference to `procps_vmstat_get'
    /usr/bin/ld: ../lib/libutils.a(vminfo_procps.o): in function `proc_vmem_get_pgpgout':
    vminfo_procps.c:(.text+0x167): undefined reference to `procps_vmstat_get'
    /usr/bin/ld: ../lib/libutils.a(vminfo_procps.o):vminfo_procps.c:(.text+0x19a): more undefined references to `procps_vmstat_get' follow
    collect2: error: ld returned 1 exit status

Also add a documentation page for developers because the procps-ng newlib
library is still in development and there's no stable version available.

Signed-off-by: Davide Madrisan <davide.madrisan@gmail.com>