tests/tslib_uname: fix a build error on Alpine Linux
The musl libc shipped by Alpine Linux does not define _UTSNAME_RELEASE_LENGTH
and thus make the build end with the following error:

  CC       tslib_uname.lo
tslib_uname.c: In function 'uname':
tslib_uname.c:32:39: error: '_UTSNAME_RELEASE_LENGTH' undeclared (first use in this function)
   32 |   strncpy (__name->release, krelease, _UTSNAME_RELEASE_LENGTH);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~
tslib_uname.c:32:39: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:958: tslib_uname.lo] Error 1
make[1]: *** [Makefile:419: all-recursive] Error 1
make: *** [Makefile:351: all] Error 2

Use the value hardcoded in /usr/include/sys/utsname.h to fix the build.

Signed-off-by: Davide Madrisan <davide.madrisan@gmail.com>