Fix build with musl by including limits.h when PATH_MAX is used
Otherwise, the build fails with:
error: PATH_MAX undeclared (first use in this function)

Bug: https://bugs.gentoo.org/717038